### PR TITLE
Add `__rust_probestack` intrinsic

### PR DESCRIPTION
**Pull request by alexcrichton**
Will be required for rust-lang/rust#42816

### CODE REVIEW

**Comment by mattico** [comment]
Just curious: does this obsolete `___chkstk_ms`?  Was that even used in the first place?

**Comment by alexcrichton** [comment]
Nah we'll still need to keep those around. On non-Windows platforms `__rust_probestack` will be used but on Windows the `__chkstk` business is still used.

It may, however, make sense to consolidate all these intrinsics in one module

**Pull request merged**
