### PR TITLE
Implement i128 <-> float conversion functions

### PR DESCRIPTION
**Pull request by est31**
Implements {u,i}128 <-> float conversion functions.

### CODE REVIEW

**Comment by est31** [comment]
Okay, I've implemented tests locally, will push once this is merged https://github.com/japaric/cast.rs/pull/13 and a new version of cast.rs is pushed to crates.io

**Comment by japaric** [comment]
Awesome, @est31. Thanks!

@homunkulus r+

**Comment by est31** [comment]
travis is blocked by #41799

**Comment by est31** [comment]
Okay, with this PR applied, everything should work now: https://github.com/japaric/cast.rs/pull/14

**Comment by est31** [comment]
re-r? @japaric

**Comment by japaric** [comment]
@homunkulus r+

**Comment by japaric** [comment]
whoops, wrong bot

@bors r+

**Comment by est31** [comment]
re-r? @japaric

**Comment by est31** [comment]
About the thumb failure, I'm not sure whether I'm the cause of it, or whether its a spurious issue.

About the mips failure, I can reproduce it locally. Will investigate tomorrow.

**Comment by est31** [comment]
Note that the mips failure is spurious, as sometimes I can reproduce, sometimes I can't (for every try i delete the target/ dir).

As for the thumb failure, I have tried to reproduce it but got failures earlier on (sth like `error: couldn't walk the sysroot` and `caused by: IO error for operation on /rust/lib/rustlib/src: No such file or directory (os error 2)`).

**Comment by japaric** [comment]
@homunkulus r+

**Pull request merged**
