### PR TITLE
Update compiler-rt submodule

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
This brings in LLVM 5 related changes. Not tested.

### CODE REVIEW

**Comment by ishitatsuyuki** [comment]
CI failure due to homebrew failing on outdated Ruby.

**Comment by alexcrichton** [comment]
I don't think we're ready for LLVM 5 to land upstream in rustc, so why would we land this ahead of time?

**Comment by ishitatsuyuki** [comment]
There's sanitizer linkage issues; and we're behind the schedule.

**Comment by alexcrichton** [comment]
That's... not really an answer though? We can't land this until we can upgrade to LLVM 5, right?

**Comment by Amanieu** [comment]
compiler-rt doesn't depend on LLVM and can be updated independently.

**Comment by ishitatsuyuki** [comment]
* the current code base has compile issues with glibc 2.26.
* the current code base is incompatible with latest LLVM sanitizers.
* the upgrade should be back compat, but it may cause the sanitizers to fail weird. Needs test.

**Comment by alexcrichton** [comment]
Aren't the newer sanitizers not guaranteed to be compatible with older LLVM? Are we sure that this upgrade of the compiler-rt submodule actually works with the LLVM rustc is using?

**Comment by ishitatsuyuki** [comment]
Let's test it. I will open a WIP PR to rust repo tomorrow.

**Comment by alexcrichton** [comment]
According to https://github.com/rust-lang/rust/pull/45779 sounds like we're not quite ready for this, so closing

**Pull request closed without merging**
