### PR TITLE
by default, mark this crate as the #![compiler_builtins] crate

### PR DESCRIPTION
**Pull request by japaric**
as this is how most users will want to use this crate

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Hm this isn't actually used as `#[cfg(feature = "rustbuild")]` in the source, is that intentional?

**Comment by japaric** [comment]
Nah, it was wrong to begin with. I also need to update ci/run.sh to not use #![compiler_builtins] during tests. I'll update the PR once #125 lands.

**Pull request merged**
