### PR TITLE
no-std friendly test suite

### LINKED ISSUE #87: Failed to build as a dependency
Added this to my Cargo.toml

``` toml
[dependencies]
rustc_builtins = { git = "https://github.com/japaric/rustc-builtins" }
```

tried to compile using

```
RUST_BACKTRACE=1 xargo build --target=stm32f429zi --verbose
```

got this error

```
error: failed to run custom build command for `rustc_builtins v0.1.0 (https://github.com/japaric/rustc-builtins#89ebc46f)`
process didn't exit successfully: `/Users/vadzim/Downloads/rplayground/target/debug/build/rustc_builtins-c925dd23196c1b21/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs

--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', ../src/libcore/result.rs:799
stack backtrace:
   1:        0x109c560d8 - std::sys::backtrace::tracing::imp::write::h22f199c1dbb72ba2
   2:        0x109c5b56f - std::panicking::default_hook::{{closure}}::h9a389c462b6a22dd
   3:        0x109c5a605 - std::panicking::default_hook::h852b4223c1c00c59
   4:        0x109c5ab56 - std::panicking::rust_panic_with_hook::hcd9d05f53fa0dafc
   5:        0x109c5a9f4 - std::panicking::begin_panic::hf6c488cee66e7f17
   6:        0x109c5a912 - std::panicking::begin_panic_fmt::hb0a7126ee57cdd27
   7:        0x109c5a877 - rust_begin_unwind
   8:        0x109c80c30 - core::panicking::panic_fmt::h9af671b78898cdba
   9:        0x109c05c01 - core::result::unwrap_failed::hb3293571464cc40d
  10:        0x109c01575 - <core::result::Result<T, E>>::unwrap::hebcc09568bcc73ba
  11:        0x109c0fa1a - build_script_build::main::hfbb6c5966e861548
  12:        0x109c5bb2a - __rust_maybe_catch_panic
  13:        0x109c5a146 - std::rt::lang_start::h14cbded5fe3cd915
  14:        0x109c10e69 - main

error: `cargo` process didn't exit successfully
```

### LINKED ISSUE #90: Floating point add gives different results than compiler-rt on arm-unknown-linux-gnueabi
I'm still trying to figure out what was wrong with #48, and I'd like another pair of eyes on this because I have no idea what is going on.

I added an implementation of `arbitrary_float!` again, and [ran the tests](https://travis-ci.org/mattico/rustc-builtins/builds/164723455). Only [the arm-unknown-linux-gnueabi target](https://travis-ci.org/mattico/rustc-builtins/jobs/164723458#L811) failed. So I grab the arguments that made the test fail and [put them into a regular test](https://github.com/mattico/rustc-builtins/commit/1dd0832a952d2f80ef273cb819b106f1553bc431). On the next build, [the test passes](https://travis-ci.org/mattico/rustc-builtins/jobs/164727780#L784) because we're actually getting the [right answer](https://www.wolframalpha.com/input/?i=0.000000000000000000000000000000000000011540496-0.00000000000000000000000000000000000000359621) in this case. It's gcc_s and compiler-rt that have the wrong answer.

Either:
1. There's some subtle bug in the test infrastructure
2. gcc_s and libcompiler-rt both have the same bug but we don't despite the code being almost identical to compiler-rt
3. QEMU is broken but only in this specific way
4. The C compiler's optimizations cause rounding in very small numbers, but rustc does not
5. Something else?

### LINKED ISSUE #136: Removal of target dir required when adding symbols to compiler-rt-cdylib
I was attempting to add some new symbols to compiler-rt-cdylib. It worked, but the tests failed. I had to remove the target directory and do a clean re-build of the entire project to update the so file. This should not be required.

### LINKED ISSUE #144: explore using utest for testing the thumb targets
[utest](https://github.com/japaric/utest) is a custom test crate that supports `no_std` targets like the thumb targets. We could use it to test the thumb targets but there are a few complications:

- utest-cortex-m-qemu, the test runner for thumb targets that works with QEMU emulation, depends on this crate. This means that this crate will appear twice in the dependency graph and that could cause problems.

- even if we get `#[test]` working for the thumb targets, quickcheck still won't work / compile for those targets. So we'll have to create unit tests for the thumb targets that don't rely on quickcheck. We could port the compiler-builtins tests, those don't depend on quickcheck and have the advantage that we could move away from comparing compiler-builtins results to libgcc / libcompiler-rt results as well.

### PR DESCRIPTION
**Pull request by japaric**
this PR moves the test suite away from rand and quickcheck by generating the
unit tests on the host rather than on the target. Because the host is usually
x86_64 (which has hardware ops for most of the operations that need intrinsics
on other architectures), we compute the right answer on the host instead of
comparing against the libgcc_s / compiler-rt implementation on the target. With
this change, we can drop the compiler-rt-cdylib and gcc_s subprojects.

Finally we add a target specific dependency on utest, a no-std testing
framework, to additionally run the test suite on the thumb targets.

r? @alexcrichton
cc @mattico
closes #87 (we no longer depend on the rustc-cfg crate)
closes #90 (we now compare against the result of using hardware ops)
closes #136 (compiler-rt-cdylib has been removed)
closes #144 (we are now running tests on the thumb targets)

---

I have tested this locally on x86_64, ARM and the 4 thumb targets. x86_64 and
ARM pass without a problem. On all thumb targets, I had to disable the test of
the powi*f2 intrinsic as other intrinsics are needed to run that intrinsics
(cf. #154). And on thumbv6, I had to disable several tests due to the debug
assertion reported in #150.

### CODE REVIEW

**Comment by japaric** [comment]
I'm trying to debug this crash from the MIPS build job:

```
test divti3 ... qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```

but AFAICT, when running this unit test:

``` rust
#[test]
fn divti3() {
    // A
    for &((a, b), c) in TEST_CASES {
        // B
        let c_ = __divti3(a, b);
        assert_eq!(((a, b), c), ((a, b), c_));
    }
}
```

the program crashes *before* reaching the first iteration of the for loop (so it never reaches point B). I thought it could be may due to the size of the TEST_CASES array which contains 10_000 test cases but reducing it to 1 test case still causes the crash. Other unit tests that make use of i128 types, like multi3, work fine so I have no idea what's going on here.

**Comment by alexcrichton** [comment]
Looks great to me! It'd be nice to reduce the verbosity of the build script, but not critical. r=me when you feel like this should land.

**Comment by japaric** [comment]
So, I ignored the divti3 on MIPS to see if the other i128 tests pass I got this assertion while testing the modti3 intrinsic:

```
running 1 test
test modti3 ... FAILED

failures:

---- modti3 stdout ----
        thread 'modti3' panicked at 'assertion failed: `(left == right)` (left: `((-922337203685477580757, -922337203685477580700), -115292150460684697557)`, right: `((-922337203685477580757, -922337203685477580700), -115292150460684697557)`)', /target/mips-unknown-linux-gnu/debug/build/compiler_builtins-86a4e859175c573b/out/modti3.rs:10039
```

If you can't tell from glancing at it both the LHS and the RHS are exactly equal! Yet the assertion for equality fails.

There doesn't seem to be a problem with equality of i128. That operation doesn't even use an intrinsic on MIPS.

This program works fine on x86_64 and on MIPS:

``` rust
#![feature(i128_type)]

fn main() {
    let x: ((i128, i128), i128) = ((-922337203685477580757, -922337203685477580700), -115292150460684697557);
    let y: ((i128, i128), i128) = ((-922337203685477580757, -922337203685477580700), -115292150460684697557);

    assert_eq!(x, y);
    println!("OK");
}
```

```
$ cargo run
OK

$ cross run --target mips-unknown-linux-gnu
OK
```

Seems like this could some undefined behavior or ABI problem related to #137 as the div / mod / divmod intrinsics are all related. @est31, do you remember if that problem was MIPS specific? I'm only seeing the problem on 32-bit MIPS but not on MIPS64.

**Comment by japaric** [comment]
I don't know what's up with bors but tests have passed on [AppVeyor] and on [Travis] so I'm going to merge manually.

[AppVeyor]: https://ci.appveyor.com/project/rust-lang-libs/compiler-builtins/build/1.0.175
[Travis]: https://travis-ci.org/rust-lang-nursery/compiler-builtins

**Pull request merged**
