### PR TITLE
fix debug assertion in modsi3 / moddi3

### LINKED ISSUE #151: modsi3: debug assertion
``` rust
#[test]
fn modsi3() {
    let (a, b) = (-2147483648, 1798783296);
    let c_ = __modsi3(a, b);
}
```

```
running 1 test
test modsi3 ... FAILED

failures:

---- modsi3 stdout ----
        thread 'modsi3' panicked at 'attempt to subtract with overflow', /home/japaric/.cargo/git/checkouts/compiler-builtins-ec094dc45a0179c8/9681358/src/int/sdiv.rs:38
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    modsi3

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured

error: test failed
```

### PR DESCRIPTION
**Pull request by japaric**
fixes #151
this fix is very similar to #149

r? @alexcrichton

### CODE REVIEW

**Comment by mattico** [comment]
Failure probably fixed by https://github.com/rust-lang/rust/pull/40507

**Comment by alexcrichton** [comment]
If you look closely enough the timestamps may also be correlated :)

Thanks @mattico though forgot to comment here!

**Comment by japaric** [comment]
Let's try an older nightly

@homunkulus r=alexcrichton

**Comment by japaric** [comment]
> @homunkulus r=alexcrichton

Heh, wrong bot.

@bors r=alexcrichton

**Pull request merged**
